// vue/src/components/PostItem.vue
<template>
  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">{{ post.title }}</h5>
      <p class="card-text">{{ post.body }}</p>
      <div class="text-end">
        <RouterLink :to="`/edit/${post.id}`" class="btn btn-primary me-2"
          >Edit</RouterLink
        >
        <button @click="deletePost(post)" class="btn btn-danger">Delete</button>
      </div>
    </div>
  </div>
</template>

<script setup>
const props = defineProps({
  post: {
    type: Object,
    required: true,
  },
});

const emit = defineEmits(["delete"]);

function deletePost(post) {
  if (!window.confirm("Are you sure you want to delete post?")) {
    return;
  }

  fetch(`https://jsonplaceholder.typicode.com/posts/${post.id}`).then((res) => {
    if (res.status === 200) {
      emit("delete", post);
    }
  });
}
</script>

<style lang="scss" scoped></style>

// react/src/components/PostItem.jsx
import PropTypes from 'prop-types';

export default function PostItem({
  post, 
  onDelete = () => {}
}) {

  function deletePost(post) {
    if (!window.confirm('Are you sure you want to delete post?')) {
      return;
    }

    fetch(`https://jsonplaceholder.typicode.com/posts/${post.id}`).then(
      (res) => {
        if (res.status === 200) {
          onDelete(post);
        }
      }
    );
  }

  return (
    <div className='card mb-4'>
      <div className="card-body">
        <h5 className='post-title'>{post.title}</h5>
        <p className='post-body'>{post.body}</p>
        <div className="text-end">
          <button className="btn btn-primary me-2">Edit</button>
          <button onClick={() => deletePost(post)} className="btn btn-danger">Delete</button>
        </div>
      </div>
    </div>
  )
}

PostItem.propTypes = {
  post: PropTypes.object.isRequired
}
