// react/src/components/PostForm.jsx
import { useState } from "react";
import router from "../router";

export default function PostForm() {
  const [model, setModel] = useState({
    title: "",
    body: "",
  });

  function onSubmit(ev) {
    ev.preventDefault();

    fetch("https://jsonplaceholder.typicode.com/posts", {
      method: "POST",
      body: JSON.stringify(model),
    })
      .then((res) => res.json())
      .then((res) => {
        router.navigate("/");
      });
  }

  return (
    <div>
      <form onSubmit={onSubmit}>
        <h1>Create new Post</h1>
        <div className="mb-3">
          <input
            type="text"
            className="form-control"
            onInput={(ev) => setModel({ ...model, title: ev.target.value })}
            placeholder="Post Title"
          />
        </div>
        <div className="mb-3">
          <textarea
            type="text"
            className="form-control"
            onInput={(ev) => setModel({ ...model, body: ev.target.value })}
            placeholder="Post Body"
          ></textarea>
        </div>
        <p>
          <button
            disabled={!model.title || !model.body}
            className="btn btn-success"
            type="submit"
          >
            Submit
          </button>
        </p>
      </form>
    </div>
  );
}

// vue/src/pages/PostForm.vue
<template>
  <div>
    <form @submit.prevent="onSubmit">
      <h1>Create new Post</h1>
      <div class="mb-3">
        <input
          type="text"
          class="form-control"
          placeholder="Post Title"
          v-model="model.title"
        />
      </div>
      <div class="mb-3">
        <textarea
          type="text"
          class="form-control"
          placeholder="Post Body"
          v-model="model.body"
        ></textarea>
      </div>
      <p>
        <button :disabled="!model.title || !model.body" class="btn btn-success" type="submit">Submit</button>
      </p>
    </form>
  </div>
</template>

<script setup>
import { ref } from "@vue/reactivity";
import { useRouter } from "vue-router";

const router = useRouter();

const model = ref({
  title: "",
  body: "",
});

function onSubmit() {
  fetch("https://jsonplaceholder.typicode.com/posts", {
    method: "POST",
    body: JSON.stringify(model.value),
  })
    .then((res) => res.json())
    .then((res) => {
      router.push('/')
    });
}
</script>

<style lang="scss" scoped></style>
