// react/src/pages/PostList.jsx
import { useEffect, useState } from "react"
import PostItem from "../components/PostItem.jsx"

export default function PostList() {
  const [postList, setPostList] = useState([]);

  useEffect(() => {
    fetch("https://jsonplaceholder.typicode.com/posts")
      .then((res) => res.json())
      .then((posts) => {
        setPostList(posts);
      });
    return () => {
      console.log("Destroy");
    };
  }, []);

  function onDelete(post) {
    setPostList(
      postList.filter((p) => p.id != post.id)
    );
  }

  return (
    <div>
      {postList.map((post) => (
        <PostItem key={post.id} post={post} onDelete={onDelete} />
      ))}
    </div>
  );
}

// vue/src/pages/PostList.vue
<template>
  <div>
    <PostItem v-for="post of postList" 
            :key="post.id" 
            :post="post"
            @delete="onDelete">
    </PostItem>
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue';
import PostItem from '../components/PostItem.vue';

const postList = ref([])

onMounted(() => {
  fetch('https://jsonplaceholder.typicode.com/posts')
    .then(res => res.json())
    .then(posts => {
      postList.value = posts
    })
})

function onDelete(post) {
  postList.value = postList.value.filter(p => p.id != post.id)
}
</script>

<style lang="scss" scoped>

</style>
