// react/src/pages/PostForm.jsx
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useStateContext } from "../ContextProvider";
import router from "../router";

export default function PostForm() {
  const [model, setModel] = useState({
    id: "",
    title: "",
    body: "",
  });

  const params = useParams();
  const { getSinglePost, savePost } = useStateContext();

  useEffect(() => {
    if (!params.id) {
      return;
    }
    setModel(getSinglePost(params.id))
  }, []);

  function onSubmit(ev) {
    ev.preventDefault();

    savePost(model)
    router.navigate('/')
  }

  return (
    <div>
      <p>
        <Link to="/" className="btn btn-outline-secondary">
          Go back to list
        </Link>
      </p>
      <form onSubmit={onSubmit}>
        <h1>{model.id ? "Edit Post" : "Create new Post"}</h1>
        <div className="mb-3">
          <input
            type="text"
            className="form-control"
            value={model.title}
            onInput={(ev) => setModel({ ...model, title: ev.target.value })}
            placeholder="Post Title"
          />
        </div>
        <div className="mb-3">
          <textarea
            type="text"
            className="form-control"
            value={model.body}
            onInput={(ev) => setModel({ ...model, body: ev.target.value })}
            placeholder="Post Body"
          ></textarea>
        </div>
        <p>
          <button
            disabled={!model.title || !model.body}
            className="btn btn-success"
            type="submit"
          >
            Submit
          </button>
        </p>
      </form>
    </div>
  );
}

// vue/src/pages/PostForm.vue
<template>
  <div>
    <p>
      <RouterLink to="/" class="btn btn-outline-secondary">
        Go back to list
      </RouterLink>
    </p>
    <form @submit.prevent="onSubmit">
      <h1>{{ model.id ? "Edit Post" : "Create new Post" }}</h1>
      <div class="mb-3">
        <input
          type="text"
          class="form-control"
          v-model="model.title"
          placeholder="Post Title"
        />
      </div>
      <div class="mb-3">
        <textarea
          type="text"
          class="form-control"
          v-model="model.body"
          placeholder="Post Body"
        ></textarea>
      </div>
      <p>
        <button
          :disabled="!model.title || !model.body"
          class="btn btn-success"
          type="submit"
        >
          Submit
        </button>
      </p>
    </form>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useStore } from "vuex";

const store = useStore();
const route = useRoute();
const router = useRouter();

const model = ref({
  id: "",
  title: "",
  body: "",
});

onMounted(async () => {
  if (!route.params.id) {
    return;
  }
  model.value = await store.dispatch("getSinglePost", route.params.id);
});

function onSubmit() {
  store.dispatch("savePost", model.value).then(() => {
    router.push("/");
  });
}
</script>

<style></style>
